[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@aave/=lib/aave-v3-origin/src/",
  "@uniswap/=lib/v3-periphery/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
